In [1]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf

# Chemin vers le dossier contenant les fichiers CSV
dossier = 'database/'

# Liste pour stocker les données de tous les fichiers CSV
donnees_totales = []

# Parcours de tous les fichiers dans le dossier
for fichier in os.listdir(dossier):
    if fichier.endswith('.csv'):
        chemin_fichier = os.path.join(dossier, fichier)
        # Lecture du fichier CSV et ajout des données à la liste
        donnees = pd.read_csv(chemin_fichier)
        donnees_totales.append(donnees)

# Concaténation de toutes les données en un seul DataFrame
donnees_combinees = pd.concat(donnees_totales, ignore_index=True)

In [2]:
donnees_combinees

Country  Population ISO-ALPHA-3   Latitude   Longitude  \
0                 Aruba      106721         ABW  12.521110  -69.968338   
1           Afghanistan    40204035         AFG  33.939110   67.709953   
2                Angola    32853444         AGO -11.202692   17.873887   
3              Anguilla       13446         AIA  18.220554  -63.068615   
4         Åland Islands       29447         ALA  60.250716   20.374146   
...                 ...         ...         ...        ...         ...   
9410  Wallis and Futuna       11756         WLF -13.768752 -177.156097   
9411              Samoa      198500         WSM -13.759029 -172.104629   
9412              Yemen    29839309         YEM  15.552727   48.516388   
9413       South Africa    59344934         ZAF -30.559482   22.937506   
9414             Zambia    18392554         ZMB -13.133897   27.849332   

            date  
0     2024-04-05  
1     2024-04-05  
2     2024-04-05  
3     2024-04-05  
4     2024-04-05  
...          ...  
9410  2024-04-05  
9411  2024-04-05  
9412  2024-04-05  
9413  2024-04-05  
9414  2024-04-05  

[9415 rows x 6 columns]

In [3]:
donnees_combinees['year'] = donnees_combinees['date'].apply(lambda x: int(x.split('-')[0]))
donnees_combinees['month'] = donnees_combinees['date'].apply(lambda x: int(x.split('-')[1]))
donnees_combinees['day'] = donnees_combinees['date'].apply(lambda x: int(x.split('-')[2]))

In [4]:
donnees_combinees

Country  Population ISO-ALPHA-3   Latitude   Longitude  \
0                 Aruba      106721         ABW  12.521110  -69.968338   
1           Afghanistan    40204035         AFG  33.939110   67.709953   
2                Angola    32853444         AGO -11.202692   17.873887   
3              Anguilla       13446         AIA  18.220554  -63.068615   
4         Åland Islands       29447         ALA  60.250716   20.374146   
...                 ...         ...         ...        ...         ...   
9410  Wallis and Futuna       11756         WLF -13.768752 -177.156097   
9411              Samoa      198500         WSM -13.759029 -172.104629   
9412              Yemen    29839309         YEM  15.552727   48.516388   
9413       South Africa    59344934         ZAF -30.559482   22.937506   
9414             Zambia    18392554         ZMB -13.133897   27.849332   

            date  year  month  day  
0     2024-04-05  2024      4    5  
1     2024-04-05  2024      4    5  
2     2024-04-05  2024      4    5  
3     2024-04-05  2024      4    5  
4     2024-04-05  2024      4    5  
...          ...   ...    ...  ...  
9410  2024-04-05  2024      4    5  
9411  2024-04-05  2024      4    5  
9412  2024-04-05  2024      4    5  
9413  2024-04-05  2024      4    5  
9414  2024-04-05  2024      4    5  

[9415 rows x 9 columns]

In [5]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf

# Chemin vers le dossier contenant les fichiers CSV
dossier = 'database_2/'

# Liste pour stocker les données de tous les fichiers CSV
donnees_totales = []

# Parcours de tous les fichiers dans le dossier
for fichier in os.listdir(dossier):
    if fichier.endswith('.csv'):
        chemin_fichier = os.path.join(dossier, fichier)
        # Lecture du fichier CSV et ajout des données à la liste
        donnees = pd.read_csv(chemin_fichier)
        donnees_totales.append(donnees)

# Concaténation de toutes les données en un seul DataFrame
df_new = pd.concat(donnees_totales, ignore_index=True)

In [6]:
df_new

Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0    Afghanistan               60           AF                58.10%   
1        Albania              105           AL                43.10%   
2        Algeria               18           DZ                17.40%   
3        Andorra              164           AD                40.00%   
4         Angola               26           AO                47.50%   
..           ...              ...          ...                   ...   
190    Venezuela               32           VE                24.50%   
191      Vietnam              314           VN                39.30%   
192        Yemen               56           YE                44.60%   
193       Zambia               25           ZM                32.10%   
194     Zimbabwe               38           ZW                41.90%   

    Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0          652,230           323,000       32.49          93.0   
1           28,748             9,000       11.78         355.0   
2        2,381,741           317,000       24.28         213.0   
3              468               NaN        7.20         376.0   
4        1,246,700           117,000       40.73         244.0   
..             ...               ...         ...           ...   
190        912,050           343,000       17.88          58.0   
191        331,210           522,000       16.75          84.0   
192        527,968            40,000       30.45         967.0   
193        752,618            16,000       36.19         260.0   
194        390,757            51,000       30.68         263.0   

    Capital/Major City Co2-Emissions  ... Out of pocket health expenditure  \
0                Kabul         8,672  ...                           78.40%   
1               Tirana         4,536  ...                           56.90%   
2              Algiers       150,006  ...                           28.10%   
3     Andorra la Vella           469  ...                           36.40%   
4               Luanda        34,693  ...                           33.40%   
..                 ...           ...  ...                              ...   
190            Caracas       164,175  ...                           45.80%   
191              Hanoi       192,668  ...                           43.50%   
192              Sanaa        10,609  ...                           81.00%   
193             Lusaka         5,141  ...                           27.50%   
194             Harare        10,983  ...                           25.80%   

    Physicians per thousand  Population  \
0                      0.28  38,041,754   
1                      1.20   2,854,191   
2                      1.72  43,053,054   
3                      3.33      77,142   
4                      0.21  31,825,295   
..                      ...         ...   
190                    1.92  28,515,829   
191                    0.82  96,462,106   
192                    0.31  29,161,922   
193                    1.19  17,861,030   
194                    0.21  14,645,468   

     Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                       48.90%           9.30%         71.40%   
1                                       55.70%          18.60%         36.60%   
2                                       41.20%          37.20%         66.10%   
3                                          NaN             NaN            NaN   
4                                       77.50%           9.20%         49.10%   
..                                         ...             ...            ...   
190                                     59.70%             NaN         73.30%   
191                                     77.40%          19.10%         37.60%   
192                                     38.00%             NaN         26.60%   
193                                     74.60%          16.20%         15.60%   
194   

In [28]:
df_test = pd.merge(df_new, donnees_combinees, on='Country')

In [29]:
df_test.isna().sum()

Country                                         0
Density\n(P/Km2)                                0
Abbreviation                                  140
Agricultural Land( %)                         210
Land Area(Km2)                                  0
Armed Forces size                             770
Birth Rate                                    175
Calling Code                                    0
Capital/Major City                             70
Co2-Emissions                                 210
CPI                                           560
CPI Change (%)                                525
Currency-Code                                 490
Fertility Rate                                210
Forested Area (%)                             210
Gasoline Price                                595
GDP                                            35
Gross primary education enrollment (%)        210
Gross tertiary education enrollment (%)       385
Infant mortality                              175


In [30]:
df_try = df_test[["Country", "Density\n(P/Km2)", "Land Area(Km2)", "Fertility Rate", "Infant mortality", "Life expectancy", "Population_y", "Latitude_x", "Longitude_x", "year", "month", "day"]]

In [45]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df_try['country_encoded'] = label_encoder.fit_transform(df_try['Country'])

In [46]:
df_try

Country  Density\n(P/Km2)  Land Area(Km2)  Fertility Rate  \
0     Afghanistan              60.0        652230.0            4.47   
1     Afghanistan              60.0        652230.0            4.47   
2     Afghanistan              60.0        652230.0            4.47   
3     Afghanistan              60.0        652230.0            4.47   
4     Afghanistan              60.0        652230.0            4.47   
...           ...               ...             ...             ...   
6540     Zimbabwe              38.0        390757.0            3.62   
6541     Zimbabwe              38.0        390757.0            3.62   
6542     Zimbabwe              38.0        390757.0            3.62   
6543     Zimbabwe              38.0        390757.0            3.62   
6544     Zimbabwe              38.0        390757.0            3.62   

      Infant mortality  Life expectancy  Population_y  Latitude_x  \
0                 47.9             64.5      40204035   33.939110   
1                 47.9             64.5      40207512   33.939110   
2                 47.9             64.5      40205771   33.939110   
3                 47.9             64.5      40205652   33.939110   
4                 47.9             64.5      40206874   33.939110   
...                ...              ...           ...         ...   
6540              33.9             61.2      14870466  -19.015438   
6541              33.9             61.2      14870825  -19.015438   
6542              33.9             61.2      14869543  -19.015438   
6543              33.9             61.2      14871059  -19.015438   
6544              33.9             61.2      14869758  -19.015438   

      Longitude_x  year  month  day  country_encoded  
0       67.709953  2024      4    5                0  
1       67.709953  2024      4    5                0  
2       67.709953  2024      4    5                0  
3       67.709953  2024      4    5                0  
4       67.709953  2024      4    5                0  
...           ...   ...    ...  ...              ...  
6540    29.154857  2024      4    5              178  
6541    29.154857  2024      4    5              178  
6542    29.154857  2024      4    5              178  
6543    29.154857  2024      4    5              178  
6544    29.154857  2024      4    5              178  

[6265 rows x 13 columns]

In [31]:
df_try = df_try.dropna()
df_try['Land Area(Km2)'] = df_try['Land Area(Km2)'].str.replace(',', '').astype(float)
df_try['Density\n(P/Km2)'] = df_try['Density\n(P/Km2)'].str.replace(',', '').astype(float)

In [20]:
from sklearn.preprocessing import MinMaxScaler

# Créer un objet MinMaxScaler
scaler = MinMaxScaler()

# Appliquer la normalisation aux colonnes de votre dataframe (sauf la colonne d'index si elle n'est pas numérique)
df_normalized = df_try[["Density\n(P/Km2)", "Land Area(Km2)", "Fertility Rate", "Infant mortality", "Life expectancy", "Latitude_x", "Longitude_x", "year", "month", "day", "Population_y", "country_encoded"]].copy()  # Faites une copie du dataframe original pour conserver les données non normalisées
df_normalized[df_normalized.columns] = scaler.fit_transform(df_normalized[df_normalized.columns])

# Afficher le dataframe normalisé
print(df_normalized)

      Density\n(P/Km2)  Land Area(Km2)  Fertility Rate  Infant mortality  \
0             0.006941        0.038143        0.588533          0.559567   
1             0.006941        0.038143        0.588533          0.559567   
2             0.006941        0.038143        0.588533          0.559567   
3             0.006941        0.038143        0.588533          0.559567   
4             0.006941        0.038143        0.588533          0.559567   
...                ...             ...             ...               ...   
6540          0.004308        0.022850        0.445194          0.391095   
6541          0.004308        0.022850        0.445194          0.391095   
6542          0.004308        0.022850        0.445194          0.391095   
6543          0.004308        0.022850        0.445194          0.391095   
6544          0.004308        0.022850        0.445194          0.391095   

      Life expectancy  Latitude_x  Longitude_x  year  month  day  Population_y  
0     

In [47]:
X = df_try[["Density\n(P/Km2)", "Land Area(Km2)", "Fertility Rate", "Infant mortality", "Life expectancy", "Latitude_x", "Longitude_x", "year", "month", "day", "country_encoded"]].values
y = df_try["Population_y"].values.reshape(-1, 1)
train_ratio = 0.8
train_size = int(len(X) * train_ratio)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

In [ ]:
X = df_normalized[["Density\n(P/Km2)", "Land Area(Km2)", "Fertility Rate", "Infant mortality", "Life expectancy", "Latitude_x", "Longitude_x", "year", "month", "day"]].values
y = df_normalized["Population_y"].values.reshape(-1, 1)
train_ratio = 0.8
train_size = int(len(X) * train_ratio)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

In [22]:
X_train[0]

array([0.00694112, 0.0381426 , 0.58853288, 0.55956679, 0.35889571,
       0.70694423, 0.68761236, 0.        , 0.        , 0.        ])

In [48]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu', input_shape = 100),
    tf.keras.layers.Dense(1)  # Couche de sortie sans activation pour une régression
])

# Compiler le modèle
model.compile(optimizer='adam', loss='mean_squared_error')

# Entraîner le modèle
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

# Évaluer le modèle sur l'ensemble de test
loss = model.evaluate(X_test, y_test)
print("Loss sur l'ensemble de test:", loss)

# Faire des prédictions sur l'ensemble de test
predictions = model.predict(X_test)

# Afficher quelques prédictions
for i in range(10):
    print("Vraie valeur:", y[i][0], "| Prédiction:", predictions[i][0])

Epoch 1/50


C:\Users\jujuc\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


141/141 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 37104862420271104.0000 - val_loss: 812587679744000.0000
Epoch 2/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32082033459068928.0000 - val_loss: 2212972638240768.0000
Epoch 3/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21965493543895040.0000 - val_loss: 26458141004660736.0000
Epoch 4/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21894259363807232.0000 - val_loss: 44292232492089344.0000
Epoch 5/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23479967731941376.0000 - val_loss: 46637623938121728.0000
Epoch 6/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26248050531893248.0000 - val_loss: 52007359555305472.0000
Epoch 7/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18691989729968128.0000 - val_loss: 52444943708323840.0000
Epoch 8/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24584175906455552.0000 - val_loss: 48719819788255232.0000
Epoch 9/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1960554860

In [49]:
predictions

array([[ 3847445.2],
       [ 3847445.2],
       [ 3847445.2],
       ...,
       [23396656. ],
       [23396656. ],
       [23396656. ]], dtype=float32)

In [43]:
model.predict(X_pred)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[1.68553104e+08],
       [1.73488512e+09],
       [4.72426592e+08],
       [1.10780592e+08],
       [7.61196736e+08],
       [1.98638180e+07],
       [4.82873651e+09],
       [2.54565872e+08],
       [5.14963328e+08],
       [3.63694752e+08],
       [1.41216350e+06],
       [2.46681775e+06],
       [2.44609504e+08],
       [3.67035744e+08],
       [4.99462144e+08],
       [1.23210780e+07],
       [6.86030464e+08],
       [8.51877400e+06],
       [5.31179725e+09],
       [2.68285125e+06],
       [7.48931360e+07],
       [4.70289888e+08],
       [2.53323100e+06],
       [7.78432384e+08],
       [1.89413780e+07],
       [8.02435840e+08],
       [5.91729792e+08],
       [2.89577280e+08],
       [1.28967025e+06],
       [1.84917500e+07],
       [1.75892440e+07],
       [1.77778144e+08],
       [1.67846624e+08],
       [1.18877837e+09],
       [3.62905216e+08],
       [5.40161550e+06],
       [1.51347392e+08],
       [1.84429260e+07],
       [1.48599775e+06],
       [1.96864075e+06],


In [44]:
X_pred[0]

array([-4.09005570e+01,  1.74885971e+02,  1.80000000e+01,  2.68838000e+05,
        1.71000000e+00,  4.70000000e+00,  8.19000000e+01,  2.02400000e+03,
        6.00000000e+00,  1.00000000e+00])

In [24]:
# Prédict data 
df_pred = df_try[["Density\n(P/Km2)", "Land Area(Km2)", "Fertility Rate", "Infant mortality", "Life expectancy", "Latitude_x", "Longitude_x", "year", "month", "day"]]
unique_combinations = df_pred.groupby(['Latitude_x', 'Longitude_x']).first().reset_index()
unique_combinations["year"] = 2024
unique_combinations["month"] = 6
unique_combinations["day"] = 1

df_normalized = df_pred.copy()  # Faites une copie du dataframe original pour conserver les données non normalisées
df_normalized[df_normalized.columns] = scaler.fit_transform(df_normalized[df_normalized.columns])


X_pred = df_normalized.values

predictions = model.predict(X_pred)

196/196 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [25]:
predictions

array([[0.0293266 ],
       [0.0293266 ],
       [0.0293266 ],
       ...,
       [0.0050635 ],
       [0.0050635 ],
       [0.00506349]], dtype=float32)

In [ ]:
predictions_denormalized = predictions_normalized * (max_target - min_target) + min_target

In [50]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # Initialisation des poids
        self.weights_input_hidden = np.random.randn(input_size, hidden_size)
        self.weights_hidden_output = np.random.randn(hidden_size, output_size)
        # Initialisation des biais
        self.bias_hidden = np.zeros(hidden_size)
        self.bias_output = np.zeros(output_size)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def rmse_loss(self, y_true, y_pred):
        return np.sqrt(np.mean(np.square(y_true - y_pred)))

    def forward(self, X):
        # Calcul de la sortie de la couche cachée
        hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = self.sigmoid(hidden_input)
        # Calcul de la sortie finale
        output_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        predicted_output = self.sigmoid(output_input)
        return predicted_output

    def backward(self, X, y, predicted_output, learning_rate):
        # Calcul de l'erreur
        error = y - predicted_output
        # Calcul du gradient de l'erreur par rapport à la sortie
        delta_output = error * self.sigmoid_derivative(predicted_output)
        # Calcul du gradient de l'erreur par rapport à la couche cachée
        error_hidden = np.dot(delta_output, self.weights_hidden_output.T)
        delta_hidden = error_hidden * self.sigmoid_derivative(self.hidden_output)
        # Mise à jour des poids et des biais
        self.weights_hidden_output += np.dot(self.hidden_output.T, delta_output) * learning_rate
        self.weights_input_hidden += np.dot(X.T, delta_hidden) * learning_rate
        self.bias_output += np.sum(delta_output, axis=0) * learning_rate
        self.bias_hidden += np.sum(delta_hidden, axis=0) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            # Passage avant
            predicted_output = self.forward(X)
            # Passage arrière
            self.backward(X, y, predicted_output, learning_rate)
            # Calcul de la perte (loss)
            loss = self.rmse_loss(y, predicted_output)
            if epoch % 100 == 0:
                print(f'Epoch {epoch}, Loss: {loss:.4f}')

# Exemple d'utilisation
# Supposons que X soit vos caractéristiques et y soit votre colonne cible (la taille de la population)

input_size = X_train.shape[1]
hidden_size = 100  # Taille de la couche cachée
output_size = 1  # Taille de la sortie
learning_rate = 0.1
epochs = 1000

# Initialisation du réseau de neurones
nn = NeuralNetwork(input_size, hidden_size, output_size)

# Entraînement du réseau de neurones
nn.train(X_train, y_train, epochs, learning_rate)

# Faire des prédictions
predictions = nn.forward(X)
print("Prédictions:")
print(predictions)

C:\Users\jujuc\AppData\Local\Temp\ipykernel_17652\964405654.py:13: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Epoch 0, Loss: 171655492.7216
Epoch 100, Loss: 171655492.7214
Epoch 200, Loss: 171655492.7214
Epoch 300, Loss: 171655492.7214
Epoch 400, Loss: 171655492.7214
Epoch 500, Loss: 171655492.7214
Epoch 600, Loss: 171655492.7214
Epoch 700, Loss: 171655492.7214
Epoch 800, Loss: 171655492.7214
Epoch 900, Loss: 171655492.7214
Prédictions:
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [36]:
X_train.shape[1]

10

In [34]:
predictions[0]

array([1.])

In [27]:
predictions[0]

array([3.91282978e-85])

In [16]:
y_train

array([[40204035],
       [40207512],
       [40205771],
       ...,
       [ 5457561],
       [ 5457729],
       [ 5457918]], dtype=int64)

In [17]:
print(predictions[0])

[1.]


In [57]:
df_pred = df_try[["Density\n(P/Km2)", "Land Area(Km2)", "Fertility Rate", "Infant mortality", "Life expectancy", "Latitude_x", "Longitude_x", "year", "month", "day", "country_encoded"]]

In [58]:
unique_combinations = df_pred.groupby(['Latitude_x', 'Longitude_x']).first().reset_index()
unique_combinations["year"] = 2024
unique_combinations["month"] = 6
unique_combinations["day"] = 1
unique_combinations

Latitude_x  Longitude_x  Density\n(P/Km2)  Land Area(Km2)  \
0    -40.900557   174.885971              18.0        268838.0   
1    -38.416097   -63.616672              17.0       2780400.0   
2    -35.675147   -71.542969              26.0        756096.0   
3    -32.522779   -55.765835              20.0        176215.0   
4    -30.559482    22.937506              49.0       1219090.0   
..          ...          ...               ...             ...   
174   60.128161    18.643501              25.0        450295.0   
175   60.472024     8.468946              15.0        323802.0   
176   61.524010   105.318756               9.0      17098240.0   
177   61.924110    25.748151              18.0        338145.0   
178   64.963051   -19.020835               3.0        103000.0   

     Fertility Rate  Infant mortality  Life expectancy  year  month  day  \
0              1.71               4.7             81.9  2024      6    1   
1              2.26               8.8             76.5  2024      6    1   
2              1.65               6.2             80.0  2024      6    1   
3              1.97               6.4             77.8  2024      6    1   
4              2.41              28.5             63.9  2024      6    1   
..              ...               ...              ...   ...    ...  ...   
174            1.76               2.2             82.5  2024      6    1   
175            1.56               2.1             82.8  2024      6    1   
176            1.57               6.1             72.7  2024      6    1   
177            1.41               1.4             81.7  2024      6    1   
178            1.71               1.5             82.7  2024      6    1   

     country_encoded  
0                110  
1                  5  
2                 32  
3                171  
4                145  
..               ...  
174              152  
175              115  
176              128  
177               53  
178               68  

[179 rows x 11 columns]

In [59]:
X_pred = unique_combinations.values

In [ ]:
real_predictions = nn.forward(X_pred)

In [52]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Entraînement du modèle
rf_model.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
predictions = rf_model.predict(X_test)

# Calcul de la RMSE (Root Mean Squared Error)
rmse = mean_squared_error(y_test, predictions, squared=False)
print("RMSE:", rmse)

C:\Users\jujuc\AppData\Local\Temp\ipykernel_17652\418301095.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train, y_train)


RMSE: 34759157.70244452


In [55]:
predictions

array([ 5457439.99045575,  5457439.99045575,  5457439.99045575, ...,
       21033433.94966144, 21033433.94966144, 21033433.94966144])

In [61]:
predictions = rf_model.predict(X_pred)
predictions

array([ 66406.55926094,  64668.43873838,  66312.513669  ,  65216.31041526,
       189702.24289713, 190039.68414387,  65806.02662162, 189513.47833609,
       189568.41995115, 190579.99475344,  86850.26529447,  87252.56190384,
       189702.24289713, 190579.99475344, 190579.99475344, 190965.05029294,
       190579.99475344, 190087.29843663,  64068.10526923,  86850.26529447,
       190579.99475344, 189702.24289713, 190579.99475344, 190579.99475344,
       190087.29843663,  64077.37756797, 189702.24289713, 190373.98912253,
        63665.80865986, 190579.99475344, 190147.38533303,  64668.43873838,
       190579.99475344, 190579.99475344, 190579.99475344,  65216.31041526,
       189702.24289713, 190579.99475344, 190579.99475344,  64668.43873838,
       189702.24289713,  66312.513669  ,  64668.43873838,  64668.43873838,
       190579.99475344, 189702.24289713, 189702.24289713, 190579.99475344,
       190039.68414387, 189702.24289713, 190965.05029294, 190579.99475344,
       190373.98912253,  

In [63]:
unique_combinations['predictions'] = predictions
unique_combinations

Latitude_x  Longitude_x  Density\n(P/Km2)  Land Area(Km2)  \
0    -40.900557   174.885971              18.0        268838.0   
1    -38.416097   -63.616672              17.0       2780400.0   
2    -35.675147   -71.542969              26.0        756096.0   
3    -32.522779   -55.765835              20.0        176215.0   
4    -30.559482    22.937506              49.0       1219090.0   
..          ...          ...               ...             ...   
174   60.128161    18.643501              25.0        450295.0   
175   60.472024     8.468946              15.0        323802.0   
176   61.524010   105.318756               9.0      17098240.0   
177   61.924110    25.748151              18.0        338145.0   
178   64.963051   -19.020835               3.0        103000.0   

     Fertility Rate  Infant mortality  Life expectancy  year  month  day  \
0              1.71               4.7             81.9  2024      6    1   
1              2.26               8.8             76.5  2024      6    1   
2              1.65               6.2             80.0  2024      6    1   
3              1.97               6.4             77.8  2024      6    1   
4              2.41              28.5             63.9  2024      6    1   
..              ...               ...              ...   ...    ...  ...   
174            1.76               2.2             82.5  2024      6    1   
175            1.56               2.1             82.8  2024      6    1   
176            1.57               6.1             72.7  2024      6    1   
177            1.41               1.4             81.7  2024      6    1   
178            1.71               1.5             82.7  2024      6    1   

     country_encoded    predictions  
0                110   66406.559261  
1                  5   64668.438738  
2                 32   66312.513669  
3                171   65216.310415  
4                145  189702.242897  
..               ...            ...  
174              152   65216.310415  
175              115   65721.452499  
176              128   65721.452499  
177               53   66312.513669  
178               68   65300.938867  

[179 rows x 12 columns]

In [70]:
df_merged = pd.merge(unique_combinations, df_try[['country_encoded', 'Country']], on='country_encoded', how='left').drop_duplicates().reset_index(drop=True)
df_merged

Latitude_x  Longitude_x  Density\n(P/Km2)  Land Area(Km2)  \
0    -40.900557   174.885971              18.0        268838.0   
1    -38.416097   -63.616672              17.0       2780400.0   
2    -35.675147   -71.542969              26.0        756096.0   
3    -32.522779   -55.765835              20.0        176215.0   
4    -30.559482    22.937506              49.0       1219090.0   
..          ...          ...               ...             ...   
174   60.128161    18.643501              25.0        450295.0   
175   60.472024     8.468946              15.0        323802.0   
176   61.524010   105.318756               9.0      17098240.0   
177   61.924110    25.748151              18.0        338145.0   
178   64.963051   -19.020835               3.0        103000.0   

     Fertility Rate  Infant mortality  Life expectancy  year  month  day  \
0              1.71               4.7             81.9  2024      6    1   
1              2.26               8.8             76.5  2024      6    1   
2              1.65               6.2             80.0  2024      6    1   
3              1.97               6.4             77.8  2024      6    1   
4              2.41              28.5             63.9  2024      6    1   
..              ...               ...              ...   ...    ...  ...   
174            1.76               2.2             82.5  2024      6    1   
175            1.56               2.1             82.8  2024      6    1   
176            1.57               6.1             72.7  2024      6    1   
177            1.41               1.4             81.7  2024      6    1   
178            1.71               1.5             82.7  2024      6    1   

     country_encoded    predictions       Country  
0                110   66406.559261   New Zealand  
1                  5   64668.438738     Argentina  
2                 32   66312.513669         Chile  
3                171   65216.310415       Uruguay  
4                145  189702.242897  South Africa  
..               ...            ...           ...  
174              152   65216.310415        Sweden  
175              115   65721.452499        Norway  
176              128   65721.452499        Russia  
177               53   66312.513669       Finland  
178               68   65300.938867       Iceland  

[179 rows x 13 columns]

In [74]:
df_merged.loc[df_merged['Country'] == 'Chile']

Latitude_x  Longitude_x  Density\n(P/Km2)  Land Area(Km2)  Fertility Rate  \
2  -35.675147   -71.542969              26.0        756096.0            1.65   

   Infant mortality  Life expectancy  year  month  day  country_encoded  \
2               6.2             80.0  2024      6    1               32   

    predictions Country  
2  66312.513669   Chile